"""multi_repo

Revision ID: 3428b2dfc0b4
Revises: 
Create Date: 2026-07-06 15:39:38.545412
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3428b2dfc0b4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_commits', sa.Integer(), nullable=True),
    sa.Column('added_lines', sa.Integer(), nullable=True),
    sa.Column('deleted_lines', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'date', name='uq_daily_stat_project_date')
    )
    op.create_table('developer_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('commit_count', sa.Integer(), nullable=True),
    sa.Column('total_added', sa.Integer(), nullable=True),
    sa.Column('total_deleted', sa.Integer(), nullable=True),
    sa.Column('total_files_changed', sa.Integer(), nullable=True),
    sa.Column('first_commit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_commit', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avg_commits_per_day', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('developer_id', 'project_id', name='uq_dev_stat')
    )
    op.create_table('monthly_statistics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_commits', sa.Integer(), nullable=True),
    sa.Column('added_lines', sa.Integer(), nullable=True),
    sa.Column('deleted_lines', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'month', 'year', name='uq_monthly_stat')
    )
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('git_url', sa.String(length=500), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('default_branch', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CLONING', 'PARSING', 'CALCULATING', 'COMPLETED', 'FAILED', 'SYNCING', name='projectstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'git_url', name='uix_project_git_url')
    )
    op.create_table('commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('developer_id', sa.UUID(), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('commit_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('insertions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('files_changed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'sha', name='uix_repository_sha')
    )
    op.create_table('commit_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commit_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('folder', sa.String(length=500), nullable=True),
    sa.Column('extension', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('added_lines', sa.Integer(), nullable=True),
    sa.Column('deleted_lines', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commit_files')
    op.drop_table('commits')
    op.drop_table('repositories')
    op.drop_table('monthly_statistics')
    op.drop_table('developer_statistics')
    op.drop_table('daily_statistics')
    op.drop_table('projects')
    op.drop_table('developers')
    # ### end Alembic commands ###
