"""Add is_excluded to Developer

Revision ID: 45d9d317065a
Revises: 3428b2dfc0b4
Create Date: 2026-07-06 16:29:59.186477
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '45d9d317065a'
down_revision: Union[str, None] = '3428b2dfc0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developers', sa.Column('is_excluded', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developers', 'is_excluded')
    # ### end Alembic commands ###
