"""add user model

Revision ID: dda96aed2a9f
Revises: 45d9d317065a
Create Date: 2026-07-06 16:58:53.698947
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'dda96aed2a9f'
down_revision: Union[str, None] = '45d9d317065a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
